name: Pulumi Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r policy-pack/requirements.bd

      - name: Install Pulumi CLI
        uses: pulumi/actions@v4

      - name: Initialize Pulumi stack
        run: pulumi stack select dev

      - name: Pulumi preview with policy pack
        run: pulumi preview --policy-pack ./policy-pack

      - name: Pulumi up with policy pack
        run: pulumi up --yes --policy-pack ./policy-pack
