name: Pulumi Deploy

on:
  push:
    branches:
      - main  # or 'dev', whichever you're using

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      AWS_REGION: us-east-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r infra/requirements.txt
          pip install -r infra/policy-pack/requirements.txt

      - name: Install Pulumi CLI
        uses: pulumi/actions@v4

      - name: Initialize Pulumi stack
        working-directory: infra
        run: pulumi stack select dev

      - name: Pulumi preview with policy pack
        working-directory: infra
        run: pulumi preview --policy-pack ./policy-pack

      - name: Pulumi up with policy pack
        working-directory: infra
        run: pulumi up --yes --policy-pack ./policy-pack
